[workspace]
members = [
    "crates/abc",
    "crates/baton",
    "crates/cas",
    "crates/chaosgarden",
    "crates/holler",
    "crates/hootenanny",
    "crates/hooteproto",
    "crates/hrcli",
    "crates/audio-graph-mcp",
    "crates/llmchat",
    "crates/llm-mcp-bridge",
    "crates/luanette",
]
resolver = "2"
